
import type { ApiEndpoint } from '../types';

export const generateOpenApiSpec = (endpoints: ApiEndpoint[]): string => {
  const paths: Record<string, any> = {};

  endpoints.forEach(endpoint => {
    if (!paths[endpoint.path]) {
      paths[endpoint.path] = {};
    }

    const method = endpoint.method.toLowerCase();
    if (method === 'unknown') return;

    paths[endpoint.path][method] = {
      summary: endpoint.description,
      description: endpoint.details,
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              example: JSON.parse(endpoint.example.response || '{}')
            }
          }
        }
      }
    };
  });

  const spec = {
    openapi: '3.0.0',
    info: {
      title: 'Extracted API',
      version: '1.0.0',
      description: 'API documentation generated by API Route Extractor'
    },
    paths
  };

  return JSON.stringify(spec, null, 2);
};

export const generatePostmanCollection = (endpoints: ApiEndpoint[]): string => {
  const items = endpoints.map(endpoint => {
    const urlParts = endpoint.path.split('/').filter(Boolean);
    
    return {
      name: `${endpoint.method} ${endpoint.path}`,
      request: {
        method: endpoint.method,
        header: [],
        url: {
          raw: `{{baseUrl}}${endpoint.path}`,
          host: ['{{baseUrl}}'],
          path: urlParts
        },
        description: endpoint.details
      },
      response: []
    };
  });

  const collection = {
    info: {
      name: 'Extracted API Collection',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    item: items,
    variable: [
      {
        key: 'baseUrl',
        value: 'http://localhost:3000',
        type: 'string'
      }
    ]
  };

  return JSON.stringify(collection, null, 2);
};

export const downloadFile = (content: string, filename: string, contentType: string) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
