import { ApiEndpoint } from '../types';

interface OpenApiSpec {
  openapi: string;
  info: {
    title: string;
    version: string;
    description: string;
  };
  paths: Record<string, Record<string, OpenApiOperation>>;
  components?: {
    securitySchemes?: Record<string, any>;
  };
}

interface OpenApiOperation {
  summary: string;
  description?: string;
  operationId?: string;
  parameters?: OpenApiParameter[];
  requestBody?: OpenApiRequestBody;
  responses: Record<string, OpenApiResponse>;
  security?: Record<string, string[]>[];
}

interface OpenApiParameter {
  name: string;
  in: 'query' | 'header' | 'path' | 'cookie';
  description?: string;
  required?: boolean;
  schema: {
    type: string;
    default?: any;
  };
}

interface OpenApiRequestBody {
  description?: string;
  content: Record<string, { schema: any }>;
}

interface OpenApiResponse {
  description: string;
  content?: Record<string, { schema: any }>;
}

export const generateOpenApiSpec = (endpoints: ApiEndpoint[]): string => {
  const spec: OpenApiSpec = {
    openapi: '3.0.0',
    info: {
      title: 'Extracted API',
      version: '1.0.0',
      description: 'API documentation generated by API Route Extractor',
    },
    paths: {},
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
        basicAuth: {
          type: 'http',
          scheme: 'basic',
        },
        apiKeyAuth: {
          type: 'apiKey',
          in: 'header',
          name: 'X-API-Key',
        },
      },
    },
  };

  endpoints.forEach((endpoint) => {
    const path = endpoint.path;
    const method = endpoint.method.toLowerCase();

    if (!spec.paths[path]) {
      spec.paths[path] = {};
    }

    const operation: OpenApiOperation = {
      summary: endpoint.description || `${endpoint.method} ${endpoint.path}`,
      description: endpoint.details,
      responses: {
        '200': {
          description: 'Successful response',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                example: endpoint.example?.response ? JSON.parse(safeJsonParse(endpoint.example.response)) : {},
              },
            },
          },
        },
      },
    };

    // Infer parameters from path (e.g., /users/{id})
    const pathParams = path.match(/{([^}]+)}/g);
    if (pathParams) {
      operation.parameters = pathParams.map((param) => ({
        name: param.replace(/[{}]/g, ''),
        in: 'path',
        required: true,
        schema: { type: 'string' },
      }));
    }

    // Infer security
    if (endpoint.authType === 'bearer') {
      operation.security = [{ bearerAuth: [] }];
    } else if (endpoint.authType === 'basic') {
      operation.security = [{ basicAuth: [] }];
    } else if (endpoint.authType === 'apiKey') {
      operation.security = [{ apiKeyAuth: [] }];
    }

    // Infer request body for POST/PUT/PATCH
    if (['post', 'put', 'patch'].includes(method) && endpoint.example?.request?.curl) {
        // Simple heuristic to check if body exists in curl
        // In a real implementation, we'd use the curlParser result
        // For now, we'll leave it as a placeholder or try to parse if possible
        // We can use the curlParser logic here if we import it, but let's keep it simple for now
        operation.requestBody = {
            content: {
                'application/json': {
                    schema: {
                        type: 'object',
                        properties: {}, 
                    }
                }
            }
        };
    }

    spec.paths[path][method] = operation;
  });

  return JSON.stringify(spec, null, 2);
};

const safeJsonParse = (str: string) => {
    try {
        return str;
    } catch {
        return '{}';
    }
}
